"""Grammars for the free-text kinds that used to be short flat lists.

Business notes, survey feedback, churn, return, cancellation and audit
reasons, delivery instructions, bank statement descriptors, chief complaints,
clinical notes, discharge instructions, social captions, blog post titles and
bodies, and email subjects. Each kind is a grammar (using the inline
``((a|b))`` and ``[[optional]]`` sugar of :class:`misata.microtext.Grammar`)
over per-row slots: names, dates, amounts, places, products, plans. Then
:func:`misata.paraphrase.vary` adds the word-level variation of its register.

A flat list of twelve sentences gave 2,000 rows twelve distinct values and a
gzip ratio of 50; these keep repeats to the rate people's writing has, and
condition on the row where the row says something (a survey score, a
ticket's issue).
"""
from __future__ import annotations

from typing import Dict, List, Optional, Sequence

import numpy as np

from misata.microtext import Grammar, MicrotextGenerator
from misata.paraphrase import vary

_RULES: Dict[str, list] = {
    # ── business / CRM notes ─────────────────────────────────────────────
    "note": [
        (3, "{who} ((requested|asked for|wanted)) {req} {when_n}[[; {next}]]."),
        (3, "((Spoke|Met|Had a call)) with {fname} ((the {role}|from {company}|at {company}|)) {when_n} ((about|re|regarding)) {topic}. {outcome}"),
        (2, "{topic_cap}: {outcome_l}.[[ {next_cap}.]]"),
        (2, "{date} - {who_l} {did} {topic}. {next_cap}."),
        (2, "{who} ((confirmed|approved|signed off on|rejected|queried)) {doc} ((#{ref}|for {month}|worth ${amount_k}|for the {plan} plan))[[ {when_n}]]."),
        (1, "((Left|Sent)) ((a voicemail|an email|a message|a text)) for {fname} {when_n}; ((no answer yet|awaiting reply|will try again {weekday}|they'll call back))."),
        (1, "((Renewal|Upsell|Expansion|Downgrade)) ((discussed|flagged|raised|on the table)) for {company} - ((${amount_k}/yr|{n}0 seats|{plan} plan|annual terms))[[, {next}]]."),
        (1, "((Invoice|PO|Contract|Quote)) {ref} ((sent|received|chased|overdue|paid)) ((on {date}|today|{when_n}))[[; {next}]]."),
        (1, "((Onboarding|Kick-off|Training|QBR|Health check)) ((booked|done|held|moved)) ((for|on)) {weekday} {time}((.| with {fname}.| at {company}.))"),
             "((Customer|Client|{fname})) ((prefers|wants|asked for)) ((email only|calls after {time}|a single invoice|quarterly billing|contact via {fname}))((.| going forward.))",
             "((Paid|Settled|Cleared)) ((invoice|balance|arrears)) {ref} ((of ${amount}|in full|in two parts)) on {date}((.| - thanks {fname}.))",
             "((Moved|Changed|Transferred)) ((billing contact|account owner|main contact)) from {fname} to {fname2} ((per|at the request of|after a call with)) ((the customer|{company}|their CFO)).",
             "((Reported|Flagged|Logged)) ((bug|outage|issue)) ((in|with)) ((exports|the API|the mobile app|SSO)) ((on {date}|at {time}|again)); ((linked to|see)) #{ticket}.",
             "((Trial|Pilot|POC)) ((extended|ends|started)) ((to|on)) {date} for {company} (({n}0 users|{plan} plan|${amount_k}))((.|; {next}.))",
             "((Champion|Sponsor|Decision maker)) is {fname} {lname} ({role}); ((procurement|legal|IT)) ((contact|lead)) is {fname2}.",
             "((Usage|Logins|Activity)) ((down|up|flat)) (({n}0%|sharply|a little)) ((since|over|in)) (({month}|the last {n} weeks|Q{n})), ((check in|flag to CSM|book a QBR)).",
             "((Asked|Wanted to know|Queried)) ((whether|if)) ((we support|we can do|there's a plan for)) ((SAML|on-prem|EU data residency|an API rate increase|a {city} office visit)).",
             "((Gift|Credit|Discount)) of ((${amount}|{n}0%|one free month)) ((applied|offered|approved)) ((for|after|because of)) ((the outage|late delivery|a billing error)) on {date}."],
    "who": ["{fname}", "Customer", "Client", "{fname} ({role})", "The account owner", "Their finance team",
            "Procurement at {company}", "Our AE", "The ops lead", "Support", "Legal", "{fname} from {company}"],
    "who_l": ["{fname}", "customer", "client", "their finance team", "procurement", "our AE", "the ops lead", "legal"],
    "role": ["CFO", "ops manager", "IT lead", "head of sales", "office manager", "founder", "buyer",
             "procurement lead", "finance director", "COO", "admin", "project lead", "marketing manager"],
    "req": ["a follow-up call", "an updated quote", "a copy of the contract", "a demo for their team",
            "a discount on renewal", "more seats", "a pause on billing", "the security questionnaire",
            "a training session", "an invoice in EUR", "net-60 terms", "a sandbox account",
            "a callback", "the SLA document", "pricing for {n}0 users"],
    "when_n": ["today", "this morning", "yesterday", "on {date}", "on {weekday}", "last week", "at {time}",
               "after the demo", "on the {month} call", "during the QBR", "before month-end"],
    "topic": ["billing", "the renewal", "pricing", "the integration", "onboarding", "the {plan} plan",
              "their {n}0-seat rollout", "data migration", "the outage on {date}", "SSO setup",
              "the invoice {ref}", "contract terms", "a feature request", "user training", "their budget for {month}"],
    "topic_cap": ["Billing", "Renewal", "Pricing", "Integration", "Onboarding", "{plan} plan", "Migration",
                  "SSO", "Contract", "Budget", "Support", "Usage", "Security review"],
    "outcome": ["((They|Customer|Client)) ((are|is)) ((happy|keen|unsure|concerned|ready)) to ((proceed|renew|expand|wait until {month})).",
                "((Agreed|Settled|Landed)) on ((${amount_k}|{n}0 seats|a {n}-month term|monthly billing)).",
                "((Need|Needs|Waiting on)) ((sign-off|budget approval|legal review|a PO)) from {fname}.",
                "((No|Nothing)) ((blockers|issues|concerns)) ((raised|so far|right now)).",
                "((Risk|Churn risk|Escalation risk)): ((low|medium|high))((.|, keep an eye on it.))"],
    "outcome_l": ["agreed ((${amount}|{n}0 seats|monthly terms))", "waiting on ((sign-off|a PO|budget))",
                  "no blockers ((yet|so far))", "risk ((low|medium|high))", "((sorted|done|closed)) ((on {date}|today))"],
    "did": ["discussed", "reviewed", "queried", "approved", "escalated", "raised", "chased", "closed out"],
    "doc": ["the quote", "invoice", "the renewal", "the PO", "the contract", "the order", "the credit note",
            "the SOW", "the change request"],
    "next": ["follow up {weekday}", "send recap", "loop in {fname}", "book a call for {date}",
             "chase on {date}", "update the CRM", "share pricing", "no further action", "check back in {month}"],
    "next_cap": ["Follow up {weekday}", "Recap sent", "Next call {date}", "Chase on {date}",
                 "Pricing to follow", "No further action", "Check back in {month}", "{fname} to confirm"],

    # ── survey / NPS feedback, by sentiment ─────────────────────────────
    "feedback_pos": [
        "{fb_open_pos} {fb_point_pos}[[ {fb_point_pos2}]]",
        "{fb_point_pos} {fb_close_pos}",
        "{fb_open_pos} {fb_point_pos} {fb_wish}",
             "{fb_point_pos} {fb_point_pos2} {fb_close_pos}",
             "((Since|After)) ((switching|moving|upgrading)) to the {plan} plan in {month}, {fb_point_pos_l}",
             "{fb_open_pos} ((Especially|Particularly|Mostly)) {fb_area_l}((.|!))"],
    "feedback_mid": [
        "{fb_point_pos} ((But|However|That said,)) {fb_point_neg_l}",
        "{fb_point_neg} {fb_wish}", "((It's|It is)) ((fine|ok|decent)) ((overall|for now|for the price)). {fb_wish}",
    ],
    "feedback_neg": [
        "{fb_open_neg} {fb_point_neg}[[ {fb_point_neg2}]]",
        "{fb_point_neg} {fb_close_neg}",
             "{fb_point_neg} {fb_point_neg2} {fb_close_neg}",
             "((Since|After)) the ((update|price change|migration)) in {month}, {fb_point_neg_l} {fb_close_neg}"],
    "fb_open_pos": ["((Great|Excellent|Really good|Solid)) ((product|tool|service|experience)) ((overall|so far|for our team))((.|!))",
                    "((Love|Really like|Big fans of)) ((the product|it|this tool))((.|!))", "((Very|Really|Super)) ((happy|pleased|satisfied))((.|!))",
                    "((Been using it|We've used it)) for {n} ((months|years)) ((and love it|with no complaints|happily)).",
             "((Five|5|Ten|10)) ((stars|out of ten|/10)) from ((me|our team|the {fb_team} team))((.|!))",
             "((Honestly|Genuinely|Truly)) ((the best|one of the best|the most useful)) ((tool|thing|app)) ((we use|we've bought|in our stack))((.|!))"],
    "fb_open_neg": ["((Disappointed|Frustrated|Not happy)) ((lately|this quarter|since {month}))((.|, honestly.))",
                    "((Honestly|Sadly|Unfortunately)), ((it's gone downhill|it's not working for us|we're struggling with it)).",
             "((Two|2|Three|3)) ((out of ten|/10|stars)), ((sorry|honestly|at best)).",
             "((We're|I'm)) ((close to|thinking about|about to)) ((cancelling|leaving|switching))((.|, sadly.))"],
    "fb_point_pos": ["{fb_area} ((is|has been)) ((excellent|really smooth|quick|easy|reliable|a big improvement))((.| since {month}.))",
                     "((The|Your)) support team ((sorted|fixed|answered)) ((our issue|everything|my question)) ((within an hour|the same day|on the first reply)).",
                     "((Setting up|Rolling out|Onboarding)) {n}0 ((users|people|staff)) took ((an afternoon|less than a day|no time)).",
                     "((Saves|Has saved)) ((us|our team|me)) ((hours|a day|{n} hours)) ((every week|a month|per report)).",
             "((Our|My)) ((team|ops team|sales team|finance team)) of {n}0 ((uses|relies on|lives in)) it ((daily|every morning|all day)) ((for reporting|for planning|to track orders)).",
             "((The|Your)) {version} ((release|update)) ((fixed|sorted|improved)) ((our biggest issue|the export bug|load times)) ((overnight|completely|noticeably)).",
             "((Thanks|Shout out|Kudos)) to {fname} ((in support|on the CS team|from onboarding)) ((for|who)) ((sorting our SSO|fixing the sync|being brilliant)).",
             "((Loved|Really liked|Appreciated)) ((the|how)) ((quick setup|clean design|price|customer care|attention to detail))[[ - {fname} was great]].",
             "((Reports|Exports|Invoices)) that used to take ((hours|a day|{n} hours)) now take ((minutes|seconds|no time)).",
             "((Setup|Migration|Switching over)) from ((our old tool|spreadsheets|{company}'s system)) took ((a weekend|two days|an afternoon|{n} hours))((.|, painless.))",
             "((Our|The)) ((finance|ops|support|sales)) team ((loves|uses|depends on)) ((the {fb_area_l}|the reports|the mobile app)) ((every day|daily|for month-end)).",
             "((Uptime|Reliability|Speed)) ((has been|is)) ((rock solid|excellent|really good)) ((since|over|for)) (({month}|the last {n} months|the whole year))."],
    "fb_point_pos_l": ["((reporting|the dashboard|our workflow|everything)) ((has been|feels|is)) ((faster|smoother|so much easier))((.| for our {n}0 users.))",
                       "((support|onboarding|billing)) ((has been|is)) ((great|excellent|painless))((.|, thanks {fname}.))"],
    "fb_point_pos2": ["{fb_area} ((is|feels)) ((intuitive|clean|well thought out|fast))((.|, too.))",
                      "((Billing|Pricing)) is ((clear|fair|predictable))."],
    "fb_point_neg": ["{fb_area} ((is|has been)) ((slow|buggy|confusing|unreliable|down too often))((.| since {month}.| on {device}.))",
                     "((Support|Your team)) took ((days|{n} days|a week)) to ((reply|respond|fix anything)).",
                     "((The|Our)) ((price|bill|renewal)) ((went up|jumped|doubled)) ((without warning|by {n}0%|in {month})).",
                     "((We|I)) ((lost|had to redo)) ((data|a week's work|reports)) after ((the {version} update|an outage on {date}|a sync failure)).",
             "((Ticket|Case)) #{ticket} ((has been|was)) open ((for|since)) (({n} weeks|{date}|ages)) ((with no update|and nobody replies|with no fix)).",
             "((Price|Cost)) per seat ((went from|jumped to|is now)) ${amount} ((for the {plan} plan|this year|since {month})), ((hard to justify|too much for us|not sustainable)).",
             "((Lost|Missing)) ((data|orders|records)) from {date} ((after|during)) ((the outage|an update|a sync failure)) ((still not restored|never recovered|cost us a day)).",
             "((Every|Each)) ((Monday|month-end|morning)) ((the|our)) ((sync|report|dashboard)) ((breaks|fails|is late)) ((and|so)) ((we|I)) ((redo it by hand|chase support|lose time)).",
             "((The|Your)) ((app|site|portal)) ((logs me out|forgets my settings|crashes)) ((on|in)) ((my {device}|{browser}|the train|every update)).",
             "((We|I)) ((pay|are paying)) ${amount} ((a month|per seat|per user)) and ((still|yet)) ((can't|cannot)) ((export to PDF|set permissions|use SSO|get a reply)).",
             "((Search|Filters|The calendar|Sync)) ((misses|loses|drops)) ((items|bookings|records|half our data)) ((randomly|most weeks|since {version})).",
             "((Onboarding|Training|Docs)) ((was|were)) ((thin|confusing|out of date)) - ((took|cost)) us (({n} weeks|a month|ages)) to ((get going|work it out|go live))."],
    "fb_point_neg_l": ["{fb_area_l} ((is|has been)) ((slow|buggy|confusing|unreliable))((.| lately.))",
                       "support ((is|was)) slow to ((reply|respond))."],
    "fb_point_neg2": ["{fb_area} ((keeps|still)) ((crashing|timing out|logging us out))."],
    "fb_team": ["finance", "ops", "support", "sales", "marketing", "product", "HR", "warehouse"],
    "fb_area": ["The dashboard", "Reporting", "The mobile app", "Search", "The API", "Onboarding", "The {plan} plan",
                "The Slack integration", "Exports", "Permissions", "Invoicing", "Scheduling", "The new editor",
             "The {month} release",
             "Approvals",
             "The calendar view",
             "Notifications",
             "Two-factor login",
             "The Xero sync",
             "Bulk import",
             "Templates"],
    "fb_area_l": ["the dashboard", "reporting", "the mobile app", "search", "the API", "exports", "permissions", "invoicing",
             "approvals",
             "notifications",
             "the calendar view",
             "bulk import",
             "templates",
             "the Xero sync",
             "the iPad app"],
    "fb_wish": ["((Would love|Please add|We need|Wish there was)) ((dark mode|better exports|SSO|an Android app|bulk editing|more integrations|offline mode))((.|!| soon.))",
                "((Would be|It'd be)) ((perfect|five stars|ten out of ten)) with ((better reporting|faster support|a lower price)).",
             "((If|Once)) ((you add|there's|we get)) ((SSO|a public API|role permissions|Xero sync|an iPad app)), ((we'll|I'll|we will)) ((upgrade|renew|stay))."],
    "fb_close_pos": ["((Keep it up|Keep up the good work|Thanks, team))((.|!))", "((Would|Will)) ((recommend|renew|expand our plan))((.|!))"],
    "fb_close_neg": ["((Considering|Looking at|Evaluating)) ((alternatives|other tools|cancelling)) ((at renewal|in {month}|now)).",
                     "((Fix|Sort)) this ((please|or we'll leave|soon))((.|!))"],

    # ── reasons ──────────────────────────────────────────────────────────
    "churn": ["((Too expensive|Price went up|Budget cut|Couldn't justify the cost))((| for our team| after the {month} increase| at {n}0 seats))",
              "((Switched|Moved|Migrated)) to ((a competitor|another tool|an in-house solution|a cheaper plan))[[ in {month}]]",
              "((Not using it|Low usage|Team stopped using it))((| enough| since {month}| after {fname} left))",
              "((Missing|Lacked|Needed)) ((integrations|SSO|reporting|an API|mobile support|bulk editing))",
              "((Company|Business|Team)) ((closed|downsized|was acquired|merged))((| in {month}| this year))",
              "((Too many|Constant|Repeated)) ((bugs|outages|support delays))((| since {version}| this quarter))",
              "((Project|Contract|Pilot)) ((ended|finished|wasn't renewed))((| in {month}| on {date}))",
              "((Only|Just)) needed it for ((one project|a short trial|a single event|{month}))",
             "((Moving|Moved)) ((our|the)) team to ((Notion|a spreadsheet|the parent company's tool|Google Workspace))((| from {month}| after the merger))",
             "((Owner|Admin|Our champion)) {fname} ((left the company|moved roles|went on leave))((| in {month}| last {weekday}))",
             "((Renewal|Invoice)) of ${amount} ((wasn't approved|was rejected by finance|is over budget))((| for {month}| this year))",
             "((Support|Response times|Onboarding)) ((too slow|not good enough|was a problem))((| - waited {n} days| on ticket #{ticket}))",
             "((Seasonal|Temporary|One-off)) ((business|use|project)), ((back in|will return in|closing until)) {month}",
             "((Data|Privacy|Compliance)) ((concerns|requirements|review)) ((from legal|from {company}'s security team|under GDPR))",
             "((Merged|Consolidated)) ((accounts|workspaces|licences)) into {company}'s ((main contract|enterprise plan|parent account))",
             "((Team|Company|Office)) ((relocated|moved)) to {city} and ((uses|switched to|standardised on)) ((a local provider|another vendor|their own system))",
             "((Wanted|Needed|Expected)) ((a cheaper|a monthly|a smaller)) ((plan|tier|option)) ((for {n} users|than {plan}|under ${amount}/mo))",
             "((Didn't|Never)) ((finish|complete|get through)) ((onboarding|setup|the migration))((| - stuck since {date}| after {n} weeks))"],
    "cancel": ["((Change of plans|Plans changed|Trip cancelled|Event postponed))((| - moving to {month}| due to illness| for work))",
               "((Booked|Ordered)) ((by mistake|twice|the wrong date|the wrong size))", "((Found|Got)) ((a better price|it cheaper|an alternative)) ((elsewhere|in {city}|online))",
               "((Delivery|Dispatch)) ((too slow|delayed|kept moving))((| past {date}))", "((No longer|Don't)) need ((it|the booking|this))((| after all| anymore))",
               "((Illness|Family emergency|Work commitments))((| this week| on {date}))", "((Weather|Strikes|Travel disruption)) in {city}",
             "((Flight|Train|Ferry)) ((cancelled|changed|delayed)) - ((can't make|no longer travelling on|rebooked away from)) {date}",
             "((Double|Duplicate)) booking ((made|placed)) ((on {date}|at {time}|by my partner))",
             "((Venue|Hotel|Host)) ((cancelled|changed the dates|closed)) ((on us|last minute|for {month}))",
             "((Price|Total|Fee)) ((was higher than shown|went up to ${amount}|included hidden charges))",
             "((Kids|Partner|Colleague)) ((got ill|has covid|broke a leg)), ((sorry|will rebook|hopefully next time))",
             "((Going|Travelling|Moving)) to {city} ((instead|now|that week))((| - will rebook| - sorry))",
             "((Ordered|Booked)) the {item} ((by mistake|twice|in the wrong size)) on {date}"],
    "return": ["((Too small|Too big|Wrong size|Doesn't fit))((| - need a size up| - ordered a {n}| in the shoulders))",
               "((Not as described|Looks different from the photos|Colour isn't as shown|Different material))",
               "((Arrived|Came)) ((damaged|broken|scratched|with a missing part))", "((Changed my mind|No longer needed|Bought elsewhere))",
               "((Faulty|Stopped working|Defective)) after ((a day|{n} days|first use|a week))",
               "((Wrong item|Wrong colour|Wrong model)) ((sent|received|delivered))", "((Quality|Material|Build)) ((not good enough|feels cheap|disappointing))",
               "((Late|Delayed)) ((delivery|arrival)), ((missed the event|needed it for {occasion}|too late to use))",
             "((Ordered|Bought)) ((two sizes|two colours|a few options)) ((to try|to compare)), ((returning|sending back)) the ((rest|other one|spares))",
             "((Smaller|Bigger|Darker|Lighter|Thinner)) than ((pictured|described|expected)) - {item}",
             "((Gift|Present)) ((not wanted|duplicate|didn't suit))((| - for {occasion}| from my partner))",
             "((Zip|Seam|Strap|Button|Handle)) ((broke|came off|split)) ((on first use|after {n} days|straight away))",
             "((Doesn't|Does not|Won't)) ((fit my {item}|work with my phone|match the room|go with anything))",
             "((Arrived|Came)) ((too late|after {date}|{n} days late)) for ((the trip|{occasion}|the event))",
             "((The|My)) {item} ((is|was)) ((too small|too big|the wrong colour|damaged|not what I ordered|smaller than shown))((| - order #{order}| from {date}))",
             "((Returning|Sending back)) ((the|my)) {item} - ((doesn't suit|not needed|faulty|arrived late|bought twice))"],
    "audit": ["((Manual|Admin|Supervisor)) override ((approved by|requested by|per)) {fname}((| - ticket #{ticket}| ref {ref}))",
              "((Limit|Threshold|Credit limit)) ((raised|lowered|adjusted)) to ${amount_k} ((per|after|following)) ((policy review|customer request|risk check))",
              "((Correction|Adjustment|Reversal)) of ((duplicate|incorrect|test)) ((entry|posting|charge)) {ref}",
              "((Access|Permission|Role)) ((granted|revoked|changed)) for {fname} ((by|per)) ((IT|security|the account owner))",
              "((Quarterly|Annual|Monthly)) ((reconciliation|review|attestation)) - {month}", "((Data|Record)) ((fix|update|merge)) requested by {fname} on {date}",
              "((Exception|Waiver)) ((approved|logged)) under policy ((P-{n}{n}|AML-{n}|FIN-0{n}))",
             "((Bulk|Batch|Scheduled)) ((update|import|correction)) of {n}0 ((records|accounts|invoices)) ((approved by|run by|signed off by)) {fname} on {date}",
             "((Password reset|MFA reset|Account unlock)) ((performed|approved|requested)) ((by|for)) {fname} ((via|after|following)) ((ID check|helpdesk ticket #{ticket}|manager approval))",
             "((Refund|Write-off|Credit)) of ${amount_k} ((above|over|exceeding)) ((approval limit|threshold|policy)) - ((approved|escalated to)) {fname}",
             "((Field|Value|Status)) ((changed|corrected|reset)) from ((pending|active|null|closed)) to ((approved|inactive|open|suspended)) ((by|for)) {fname} ((at|on)) {date} {time}",
             "((Export|Download|Report)) of ((customer data|invoices|PII|the {month} ledger)) ((requested|approved|run)) by {fname} ((for|re:)) ((audit|legal hold|a DSAR|the regulator))",
             "((Duplicate|Orphan|Stale)) ((record|account|invoice)) {ref} ((removed|archived|merged)) ((after|following)) ((review|data cleanse|customer request)) on {date}"],
    "delivery": ["((Leave|Drop)) ((with|at)) ((the neighbour at no. {n}|the concierge|reception|the porch|the side gate))((| if out| please))",
                 "((Ring|Knock|Call)) ((the bell|loudly|on arrival|{phone}))((| - doorbell broken| - baby sleeping| please))",
                 "((Gate|Door|Building)) code ((is|)) {n}{n}{n}{n}((| then flat {n}| - buzz {n}))", "((Do not|Don't)) leave ((on the doorstep|unattended|in the rain|with neighbours))",
                 "((Deliver|Bring it)) ((after 5pm|before 9am|between 12 and 2|after {time}|before noon))((| on weekdays| please))",
                 "((Back door|Side entrance|Rear garden)) ((- dog is friendly|via the alley|past the garage))", "((Place|Put)) ((in the safe place|behind the bins|in the shed|in the parcel box))",
             "((Neighbour|Next door|No. {n})) ((will take it|has a key|is happy to sign))((| if I'm out| - ask for {fname}))",
             "((Use|Try)) the ((buzzer for flat {n}|intercom|code {n}{n}{n}{n} on the keypad))((| then 2nd floor| then lift to floor {n}))",
             "((Please|Pls)) ((text|call)) {phone} ((when 10 min away|on arrival|before you come))",
             "((Office|Shop|Reception)) ((closes|shuts)) at ((5pm|6pm|5:30|4pm)) - ((deliver before|after that leave at the side door))",
             "((Signature|ID)) ((required|needed)) - ((parcel for {fname} {lname}|high value item|medication))",
             "((Blue|Green|Black|Red)) ((door|gate|garage)) ((next to the shop|opposite the park|at the end of the lane))",
             "((Address|Deliver to|Drop at)) {street} - ((side door|rear entrance|ground floor|basement flat))((| please))",
             "((Not|NOT)) {street}, ((it's|we're)) ((round the corner|the next building|opposite)) - ((look for|it's the)) ((blue door|house with the van|gate with a bike))"],
    "churn_detail": [" - {fname} ((said|mentioned|wrote)) ((budget is frozen until {month}|they're consolidating tools|the team shrank to {n}))",
                     " ((after|since)) ((the {month} price change|{n} years as a customer|the {version} release))",
                     " ((- {n}0 seats| - {plan} plan| - ${amount}/mo| - {plan} plan, {n}0 seats))", " - ((may come back|open to a win-back offer|won't return))"],
    "cancel_detail": [" - ((rebooked for|moving to|maybe)) {date}", " (order #{order})", " - ((refund to card {last4}|please refund ${amount}|credit is fine))",
                      ", ((sorry|thanks|apologies for the hassle))"],
    "return_detail": [" - ((ordered|bought)) {item}, ((need|want)) ((a refund|an exchange|store credit))", " (order #{order})",
                      " - ((photos attached|box kept|tags still on))", ", arrived {date}", " - ${amount} ((back to card {last4}|as credit))"],
    "delivery_detail": [" - ((thanks|cheers|ta))!", ", ((ask for|call)) {fname} ((on {phone}|at reception))", " ({street})",
                        " - ((parcel is fragile|contains glass|keep upright))", " - ((weekdays only|not on {weekday}s|any time after {time}))"],
    "discharge_detail": [" Next appointment: {date} {time}.", " ((Leaflet|Advice sheet)) given.", " ((Ring|Call)) the ward on {phone} with questions.",
                         " ((Prescription|Meds)) collected from pharmacy.", ""],
    "note_sign": [" - {initials}", " ({initials}, {date})", " -- {fname}", " [{date} {time}]", " /{initials}",
                  " - logged by {fname} {lname}", " (call ref {ref})", " #{plan}"],
    "clin_sign": [" Dr {lname}.", " - Dr {lname}, {date}", " Seen by {fname} {lname} (ANP).", " Signed: Dr {lname} ({initials}).",
                  " {date} {time}, Dr {lname}.", " Discussed with Dr {lname}."],
    "dis_sign": [" Discharging clinician: Dr {lname}.", " Ward {n} - {date}.", " Signed {fname} {lname}, staff nurse.",
                 " Reviewed by Dr {lname} on {date}."],
    "reason_frame": ["Reason: {text}", "Customer said: {text}", "Per {fname}: {text}", "{text} (via ((chat|email|phone)))",
                     "((Cust|Client|Caller)) ((says|said|mentions)) {text}", "{text} - ((logged|noted)) by {initials}",
                     "\"{text}\"", "{text} [{date}]", "Exit survey: {text}", "{text}. ((No|Not)) ((further|more)) detail ((given|provided))"],
    "audit_frame": ["[{date} {time}] {text}", "{text} ((- ref|ref:|#)) {ref}", "AUDIT: {text}", "{initials}: {text}",
                    "{text} (change #{ticket})", "Reason for override - {text}"],
    "audit_detail": [" ((per|under|ref)) ((policy|SOP|control)) ((P-{n}{n}|SEC-{n}|FIN-0{n}))", "; ((reviewed|countersigned)) by {fname2}",
                     " ((at|on)) {date} {time}", " - ((ticket|case|change)) #{ticket}", " ((for|on)) account {last4}"],
    "delivery_frame": ["Note: {text}", "{text} - thank you!", "((PLEASE|Please)) {text}", "Driver: {text}", "{text} :)"],
    # ── bank statement descriptors ──────────────────────────────────────
    "memo": ["{merch_u} #{n}{n}{n}{n} {city_u}", "POS {merch_u} {dd}/{mm}", "CARD {last4} {merch_u} {city_u}",
             "AMZN Mktp ((US|UK|DE))*{code_u}", "SQ *{small_n}", "TST* {small_n}", "PAYPAL *{small_uu}", "ACH {company_u} ((PAYROLL|DIRECT DEP|VENDOR PMT))",
             "{merch_u} ONLINE {code_u}", "CONTACTLESS {merch_u} {city_u}", "DD {company_u} REF {ref}", "FPS {fname_u} {lname_u}",
             "{merch_u} {city_u} {dd}{mon_u}", "UBER *TRIP {code_u}", "SPOTIFY P{code_u}", "APPLE.COM/BILL {code_u}",
             "INT'L {merch_u} {city_u} FX", "ATM WDL {city_u} {dd}/{mm}", "TFR TO {fname_u} {lname_u}", "REFUND {merch_u} {code_u}"],
    # ── clinical ─────────────────────────────────────────────────────────
    "complaint": ["{symptom} ((for|x|over the last|for about)) {dur}[[, {modifier}]]", "{symptom} and {symptom2} ((for|over|for the past)) {dur}",
                  "((Worsening|Intermittent|Sudden|Recurrent)) {symptom_l}[[ for {dur}]]", "((Follow-up|Review|Recheck)) ((of|for)) {condition}",
                  "{symptom} after ((a fall|lifting|exercise|a car accident|eating)) ((yesterday|{dur} ago|this morning))",
             "{symptom} ((started|began)) ((after|following)) ((a flight|a cold|a new medication|starting the gym|a fall at work)) {dur} ago",
             "((Ongoing|Persistent|Recurring)) {symptom_l} - ((no better|worse|unchanged)) ((with|despite|after)) ((ibuprofen|antibiotics|rest|physio))",
             "((Requests|Wants|Asking for)) ((repeat prescription|fit note|blood results|referral)) ((for|re:)) {condition}",
             "{symptom} ((left|right|bilateral)) ((side|knee|shoulder|ear|eye)), ((for|x)) {dur}",
             "((Child|Baby|Toddler)) ((with|has)) {symptom2} ((and|plus)) ((poor feeding|irritability|a rash|high temp)) for {dur}",
             "((Pain|Swelling|Bruising)) ((after|following)) ((a fall|a sports injury|DIY|a dog bite)) {dur} ago",
             "((Medication|Med)) ((review|query|side effects)) - {med} ((causing|with|and)) ((nausea|dizziness|a rash|low mood))",
             "((Abnormal|Raised|Low)) ((bloods|BP|sugar|potassium)) ((on|from)) ((recent test|{date}|the pharmacy check))",
             "((Recheck|Review|Follow-up)) ((of|after)) ((wound|BP|bloods|rash|chest infection)) ((from|seen on)) {date}",
             "((Seen|Treated)) ((in A&E|at urgent care|by 111|at the pharmacy)) ((on|last)) ((Sunday|{weekday}|{date})) for {symptom_l}, ((no better|still sore|wants review))",
             "{symptom} ((and|with)) {symptom2} ((since|after)) ((returning from {city}|starting {med}|a cold|a flight))"],
    "symptom": ["Chest pain", "Shortness of breath", "Headache", "Abdominal pain", "Back pain", "Fever", "Cough",
                "Dizziness", "Nausea", "Rash", "Sore throat", "Knee pain", "Palpitations", "Fatigue", "Ear pain",
                "Vomiting", "Diarrhoea", "Wrist swelling", "Eye redness", "Ankle injury", "Burning on urination",
                "Neck stiffness", "Hip pain", "Leg swelling", "Blurred vision", "Tinnitus", "Joint pain", "Itching",
                "Constipation", "Heartburn", "Insomnia", "Low mood", "Anxiety", "Weight loss", "Night sweats",
                "Numbness in the hand", "Tingling in the feet", "Toothache", "Nosebleed", "Wheeze", "Calf pain",
                "Groin pain", "Shoulder pain", "Blood in urine", "Painful periods", "Hair loss", "Mouth ulcers",
                "Swollen glands", "Earwax", "Fainting episode", "Confusion", "Bloating"],
    "symptom2": ["fever", "nausea", "dizziness", "cough", "vomiting", "chills", "headache", "fatigue", "swelling", "rash"],
    "symptom_l": ["chest pain", "headache", "abdominal pain", "back pain", "cough", "dizziness", "palpitations", "rash",
                  "shortness of breath", "sore throat", "neck pain", "hip pain", "fatigue", "joint pain", "heartburn",
                  "wheeze", "low mood", "insomnia", "nausea", "leg swelling", "ear pain", "eye pain", "itching",
                  "loose stools", "urinary frequency", "pelvic pain", "dysuria", "shoulder pain", "night sweats"],
    "dur": ["2 days", "3 days", "1 week", "4 days", "2 weeks", "48 hours", "{n} days", "{n} weeks", "10 days", "6 months"],
    "modifier": ["worse at night", "worse on exertion", "radiating to the left arm", "relieved by rest",
                 "not improved with paracetamol", "with photophobia", "after meals", "on deep breathing", "intermittent"],
    "condition": ["hypertension", "type 2 diabetes", "asthma", "COPD", "hypothyroidism", "atrial fibrillation",
                  "depression", "CKD stage 3", "eczema", "migraine", "GORD", "osteoarthritis", "type 1 diabetes",
                  "heart failure", "IBS", "psoriasis", "rheumatoid arthritis", "gout", "epilepsy", "anaemia",
                  "hyperlipidaemia", "obesity", "sleep apnoea", "PCOS", "angina", "previous stroke", "glaucoma",
                  "coeliac disease", "Crohn's disease", "hepatitis B"],
    "clinical": ["{pt} {age}{sex} ((presents with|c/o|reports)) {symptom_l} ((for|x|over)) {dur}. {exam} {vitals} {plan_c}",
                 "{age}{sex} with ((PMH|hx)) of {condition}, ((here for|presents with|seen for)) {symptom_l}. {exam} {plan_c}",
                 "((S:|Subjective:)) {symptom_l} ((for|x)) {dur}[[, {modifier}]]. ((O:|Objective:)) {vitals} ((A:|Assessment:)) {dx}. ((P:|Plan:)) {plan_c}",
                 "{exam} {vitals} ((Likely|Impression:|Working dx:)) {dx}. {plan_c}",
             "((Telephone|Video|Face-to-face)) consult. {pt} ((reports|describes|c/o)) {symptom_l} ((for|over the past)) {dur}[[, {modifier}]]. ((No|Denies)) ((red flags|chest pain|fever|weight loss)). {plan_c}",
             "((Seen|Reviewed)) ((in clinic|at home|on the ward)) on {date}. {exam} {vitals} {dx_line} {plan_c}",
             "((Known|Hx of|Background:)) {condition}, ((on|taking)) {med} {dose}. ((Here|Attends|Presents)) with {symptom_l}. {vitals} {plan_c}",
             "((Pt|Patient|She|He)) ((returned from|travelled to|visited)) {city} ((last week|{n} days ago|recently)); ((now|since then)) {symptom_l}. {exam} {vitals} {dx_line} {plan_c}",
             "((Medication review|Meds review|Annual review|Chronic disease review)): {condition}. ((On|Taking)) {med} {dose_oral}[[, {med} {dose_oral}]]. {vitals} {plan_c}",
             "((Phone call|Telephone triage|eConsult)) with ((pt|patient|{fname}'s carer)) on {date} at {time}: {symptom_l} ((for|over)) {dur}. ((Advised|Booked|Arranged)) ((face-to-face review|bloods|an urgent appointment|self-care)). {fu}",
             "{age}{sex}, ((PMH|background)) {condition} and {condition2}. ((Presents|Attends|Seen)) with {symptom_l} ((for|over)) {dur}, {modifier}. {exam} {vitals} {dx_line} {plan_c}",
             "((Review|Recheck|F/u)) ((of|for)) {dx} ((seen|treated)) on {date}. ((Improving|Unchanged|Worse|Resolved)) ((with|on|since)) {med}. {vitals} {plan_c}",
             "((Carer|Daughter|Son|Partner)) ((reports|concerned about|says)) ((increased confusion|reduced mobility|poor intake|falls)) ((over|for)) {dur}. {exam} {vitals} {plan_c}"],
    "pt": ["Pt", "Patient", "The patient"], "sex": ["M", "F", "yo M", "yo F", " y/o male", " y/o female"],
    "age": ["2{n}", "3{n}", "4{n}", "5{n}", "6{n}", "7{n}", "8{n}"],
    "exam": ["((Chest|Lungs)) ((clear|clear bilaterally|with scattered wheeze|with bibasal crackles)).",
             "((Abdomen|Abdo)) ((soft, non-tender|tender in RLQ|mildly tender epigastrically|soft, BS present)).",
             "((Heart sounds|HS)) ((normal|I+II+0|regular, no murmurs)).", "((Throat|Pharynx)) ((erythematous|inflamed, no exudate|clear)).",
             "((ROM|Range of movement)) ((reduced|full|painful)) at the ((knee|shoulder|lumbar spine|wrist)).",
             "((Skin|Rash)) ((maculopapular|urticarial|well-demarcated)) over the ((trunk|arms|legs)).",
             "((Alert|Comfortable|Mildly distressed)) and ((orientated|well-looking|talking in full sentences)).",
             "((No|Nil)) ((focal neurology|lymphadenopathy|calf tenderness|peritonism|meningism)).",
             "((Tender|Swollen|Warm)) ((over|at|around)) the ((medial knee|lateral ankle|left wrist|right shoulder|lower back|calf))((.|, no deformity.))",
             "((Ears|TMs|Tympanic membranes)) ((normal|dull bilaterally|bulging on the left|clear))((.|; throat {throat}.))",
             "((Bowel sounds|BS)) ((present|normal|active)); ((no|nil)) ((guarding|rebound|organomegaly|masses)).",
             "((Pupils|PERLA)) ((equal and reactive|normal)); ((cranial nerves|CNs)) ((intact|grossly normal))."],
    "throat": ["clear", "mildly red", "red with exudate", "normal"],
    "vitals": ["BP {bp}, HR {hr}, T {temp}, SpO2 {spo2}%.", "Obs: BP {bp}, HR {hr}, RR {rr}, SpO2 {spo2}% RA.",
               "HR {hr}, BP {bp}, afebrile.", "T {temp}, HR {hr}, SpO2 {spo2}%."],
    "condition2": ["hypertension", "asthma", "osteoarthritis", "depression", "GORD", "hypothyroidism", "AF", "T2DM", "CKD 3a", "anxiety"],
    "dx_line": ["((Impression|Likely|Working dx|Diagnosis)): {dx}.", "((Consistent with|Suggestive of|Probable)) {dx}."],
    "dx": ["viral URTI", "musculoskeletal pain", "community-acquired pneumonia", "UTI", "gastroenteritis",
           "migraine", "mechanical back pain", "contact dermatitis", "anxiety", "sprain", "otitis media",
           "costochondritis", "tonsillitis", "acid reflux", "exacerbation of {condition}", "cellulitis",
           "sinusitis", "conjunctivitis", "tension headache", "plantar fasciitis", "tennis elbow", "sciatica",
           "irritable bowel", "viral gastroenteritis", "allergic rhinitis", "panic attack", "BPPV",
           "carpal tunnel syndrome", "gout flare", "shingles", "insect bite reaction", "acute bronchitis"],
    "plan_c": ["((Started|Prescribed|Commenced)) {med} {dose} ((BD|TDS|OD|PRN)) for {course}. {fu}",
               "((Advised|Recommended)) ((rest|fluids|ice and elevation|simple analgesia|steam inhalation)). {fu}",
               "((Referred|Refer)) to ((physio|cardiology|ENT|dermatology|ortho)) ((routine|urgent|2WW)). {fu}",
               "((Bloods|ECG|CXR|Urine dip)) ((ordered|sent|done)), ((results to follow|normal|reviewed)). {fu}",
             "((Safety-netted|Advised|Counselled)) ((re:|about|on)) ((red flags|warning signs|when to seek help)); ((leaflet|written advice|PIL)) given. {fu}",
             "((Discussed|Agreed|Shared)) ((options|a plan|management)) with ((pt|patient|the family|{fname})); ((happy|keen|reluctant)) to ((proceed|try conservative management|wait and see)). {fu}",
             "((Repeat|Recheck)) ((bloods|U&Es|HbA1c|LFTs|FBC)) in ((2 weeks|a month|3 months|6 weeks)); ((continue|increase|reduce|stop)) {med}. {fu}",
             "((Self-care|Conservative management|Watchful waiting)) ((advised|agreed|discussed)) - ((rest|fluids|analgesia|ice|warm compresses)) for {course}. {fu}"],
    "med": ["amoxicillin", "ibuprofen", "paracetamol", "naproxen", "omeprazole", "salbutamol", "prednisolone",
            "cetirizine", "nitrofurantoin", "codeine", "sertraline", "doxycycline", "metformin", "amlodipine",
            "ramipril", "atorvastatin", "levothyroxine", "lansoprazole", "co-codamol", "flucloxacillin",
            "clarithromycin", "trimethoprim", "loratadine", "fluoxetine", "citalopram", "mirtazapine", "gabapentin",
            "tramadol", "diclofenac gel", "beclometasone", "furosemide", "bisoprolol", "apixaban", "warfarin",
            "loperamide", "senna", "lactulose", "cefalexin", "propranolol", "sumatriptan", "metoclopramide"],
    "dose": ["500mg", "400mg", "1g", "20mg", "250mg", "10mg", "50mg", "100mg", "5mg", "40mg", "200mg", "2.5mg"],
    "dose_oral": ["500mg", "400mg", "20mg", "10mg", "50mg", "100mg", "5mg", "40mg", "75mg", "25mg"],
    "course": ["5 days", "7 days", "10 days", "2 weeks", "1 month", "3 days"],
    "fu": ["((Review|F/u|Follow up)) in ((1 week|2 weeks|48h|4 weeks|3 months)).", "Safety-netting advice given.",
           "((Return|Re-present)) if ((worse|no better in {n} days|fever persists|new symptoms)).", "((GP|Clinic)) review in ((1|2|4)) weeks."],
    "discharge": ["{dis_a} {dis_b}", "{dis_a} {dis_b} {dis_c}", "{dis_b} {dis_c}"],
    "dis_a": ["((Take|Continue)) {med} {dose} ((twice daily|three times a day|once daily|as needed)) for {course}[[ with food]].",
                  "((Rest|Keep the leg elevated|Avoid heavy lifting|Stay hydrated)) for ((48 hours|a week|{n} days|the next few days)).",
                  "((Return to|Come back to|Attend)) ((A&E|the ED|urgent care|your GP)) if you ((develop|notice|have)) ((a fever over 38C|worsening pain|chest pain|bleeding|shortness of breath)).",
                  "((Follow up|Book a review|See your GP)) in ((1 week|2 weeks|10 days|a month))[[ for {fu_item}]].",
                  "((Remove|Change)) the ((dressing|bandage|splint)) ((in {n} days|after 48 hours|daily))[[ and keep it dry]].",
                  "((No driving|Avoid alcohol|No contact sport)) for ((24 hours|a week|{n} weeks)).",
             "((Take|Use)) {med} {dose} ((every|each)) ((4|6|8|12)) hours ((as needed|for pain|with water))((| - max {n} doses a day)).",
             "((Keep|Leave)) the ((wound|stitches|cast|splint)) ((clean and dry|covered|on)) ((for {n} days|until review|until {date})).",
             "((Gradually|Slowly)) ((increase|return to)) ((walking|normal activity|work|exercise)) over ((the next week|{n} days|two weeks)).",
             "((Stitches|Sutures|Staples)) ((out|to be removed)) ((at your GP|by the practice nurse|in clinic)) in ((7|10|{n})) days.",
             "((Watch|Look out)) for ((redness|swelling|discharge|increasing pain)) and ((call|contact|ring)) ((111|your GP|the ward)) if ((it spreads|it worsens|you're worried)).",
             "((Diagnosis|You were seen for|Today you were treated for)): {dx}.",
             "((Your|The)) {test_item} ((was|were)) ((normal|reassuring|mildly abnormal|unremarkable))((.|; your GP will review.))",
             "((We|The team)) ((changed|stopped|started)) {med} ((today|on {date}|during your stay))((.| - see the medication list.))",
             "((You|Your)) ((stay|admission|visit)) ((was|lasted)) ((overnight|{n} days|a few hours)) ((on|in)) ((Ward {n}|the assessment unit|the day surgery unit|A&E))((.|, thank you for your patience.))"],
    "dis_b": ["((Take|Continue)) {med} {dose} ((twice daily|at night|every morning|as needed)) ((until the course is finished|for {course}|until your review))((.| with food.))",
              "((Pain relief|Painkillers)): {med} {dose} ((up to|no more than)) ((four|three|{n})) times a day((.| if needed.))",
              "((Avoid|No)) ((driving|alcohol|swimming|lifting over 5kg|flying|contact sport)) ((for|until)) (({n} days|your follow-up|the wound has healed|{course}))((.|, please.))",
              "((Drink|Aim for)) ((plenty of fluids|2 litres of water a day|small frequent meals))((.| while you recover.))",
              "((Use|Apply|Rub in)) {med_top} ((on the area|on the rash|on the affected skin)) ((twice a day|three times daily|at bedtime)) for {course}.",
             "((Rest|Take it easy|Keep your feet up)) ((for|over)) ((the next|the coming)) ((two days|few days|weekend)) and ((avoid|skip)) ((the gym|heavy housework|work|long walks))((.| if you can.))",
             "((Do|Try)) the ((exercises|stretches|breathing exercises)) ((on the sheet|the physio showed you|in the leaflet)) ((twice a day|three times daily|every morning))((.| for {course}.))",
             "((Check|Measure|Record)) your ((blood pressure|blood sugar|temperature|weight)) ((daily|twice a day|every morning)) and ((write it down|bring the readings|call if it's above target))((.| for {n} days.))",
             "((Use|Keep using)) ((ice|a cold pack|a hot water bottle|the sling|crutches)) ((for 20 minutes|as needed|when moving|day and night)) ((for|over)) ((the next|the first)) ((48 hours|few days|week))."],
    "med_top": ["hydrocortisone cream", "fusidic acid cream", "diclofenac gel", "emollient", "clotrimazole cream",
                "aqueous cream", "chloramphenicol ointment", "mupirocin ointment", "ibuprofen gel"],
    "dis_c": ["((Seek help|Call 999|Go to A&E|Call 111)) ((straight away|urgently|immediately)) if ((you have|you notice|there is)) ((chest pain|trouble breathing|a high fever|heavy bleeding|severe headache|new weakness)).",
              "((Book|Arrange|Expect)) ((a follow-up|a review|a phone call|an appointment)) ((with your GP|in clinic|with the nurse|with {fname} in clinic)) ((in {course}|on {date}|next {weekday}))((.| at {time}.))",
              "((Your|A)) ((discharge letter|summary|results letter)) ((has been sent|will be sent|is on its way)) to ((your GP|the practice|you by post))((.| within {n} days.))",
              "((Questions|Any concerns|Worried)) ? ((Ring|Call|Phone)) ((the ward|the clinic|111|the fracture clinic)) on {phone}((.| any time.))".replace(" ?","?"),
             "((Your next|The next|A follow-up)) ((dose|injection|dressing change|blood test)) is ((due|booked)) ((on|for)) {date}((.| at {time}.| with the practice nurse.))",
             "((Bring|Take)) ((this letter|your medication list|your inhalers|your discharge summary)) ((to|when you see)) ((your GP|the pharmacist|clinic))((.| next time.))",
             "((District nurses|The community team|A nurse)) will ((visit|call|see you)) ((on|from)) {date} to ((check the wound|change the dressing|review your medication)).",
             "((Sick note|Fit note|Work note)) ((given|provided|issued)) ((for|until)) (({n} days|{date}|two weeks))((.| - hand it to your employer.))",
             "((Pharmacy|The pharmacist)) ((has|will)) ((checked|explained|label)) ((your new medicines|the doses|everything)) ((with you|before you leave|today))."],
    "test_item": ["blood test", "ECG", "X-ray", "CT scan", "ultrasound", "urine test", "blood pressure", "chest X-ray", "MRI"],
    "fu_item": ["blood results", "a wound check", "suture removal", "a BP check", "repeat bloods", "an X-ray"],
    # ── social captions ──────────────────────────────────────────────────
    "caption": ["{cap_line} {tags}", "{cap_line}", "{cap_line} {emoji}[[ {tags}]]", "{place_line} {emoji} {tags}",
             "((Golden hour|Blue hour|Late night|Early start)) in {city} {emoji}",
             "{n}k ((done|run|walked|cycled)) ((before work|before breakfast|in the rain|with {fname}))((!| {emoji}))",
             "((Happy|So proud|Excited)) to ((share|announce|say)) ((I've joined {company}|we've moved to {city}|my first {n}k))((!| {emoji}))",
             "((Lunch|Dinner|Coffee|Drinks)) at {small_n} in {city} ((was|is)) ((unreal|the best|a vibe|so good))((!| {emoji}))",
             "((New|First|Favourite)) {item} ((arrived|unboxed|in action))((!| {emoji}| - obsessed))",
             "((Missing|Already missing|Back from)) {city} ((with|and)) {fname}((| {emoji}))",
             "((Throwback|Flashback)) to ((that|our)) ((week|weekend|trip)) in {city} ((with|and)) {fname} {emoji}",
             "((Dinner|Lunch)) ((sorted|made|done)): {food} ((for {n}|for the family|in 20 minutes))((!| {emoji}))"],
    "cap_line": ["((Sunday|Saturday|Friday|Monday)) ((vibes|mood|reset|plans))((| in {city}| with {fname}))",
                 "((Finally|Just|Officially)) ((made it to|back in|moved to|landed in)) {city}((!|.|!!))",
                 "((Can't|Cannot)) ((believe|get over)) ((this view|how good this was|it's already {month}))",
                 "((New|First|Last)) ((week|day|month)) ((at the new job|of training|in {city}|of summer))",
                 "((Coffee|Brunch|Dinner|Drinks)) with {fname} ((was much needed|hit different|again))",
                 "((Trying|Made|Baked)) ((sourdough|banana bread|ramen|a lemon tart|pasta from scratch)) ((for the first time|again|at last))",
                 "((Morning|Evening|Sunset)) ((run|walk|swim|ride)) ((by the river|along the coast|in the park|up the hill))((| - {n}k done))"],
    "food": ["pesto pasta", "a Thai green curry", "homemade pizza", "shakshuka", "ramen", "tacos", "a Sunday roast",
             "lentil soup", "fish pie", "katsu curry", "a lemon drizzle", "dal", "poke bowls", "veggie lasagne"],
    "place_line": ["{city} ((in|during)) {month}", "((Back|Home)) in {city}", "((Weekend|Week)) in {city}"],
    "tags": ["#{tag}", "#{tag} #{tag2}", "#{tag} #{tag2} #{tag3}"],
    "tag": ["travel", "weekend", "foodie", "sunset", "fitness", "coffee", "goodvibes", "homemade", "citylife",
            "nature", "running", "summer", "friends", "workfromhome", "bookstagram", "throwback", "family"],
    "tag2": ["instagood", "photooftheday", "explore", "mood", "blessed", "happy", "love", "life", "wanderlust", "selfcare"],
    "tag3": ["{citytag}", "{monthtag}", "nofilter", "weekendvibes", "adventure"],
    "emoji": ["☀️", "🌊", "☕", "🍝", "🏃", "📸", "✨", "🌿", "🍂", "❄️", "🎉", "💪"],
    # ── blog / post titles and bodies ───────────────────────────────────
    "post_title": ["((How|Why)) ((I|we)) {pt_verb} {pt_obj}((| in {n} weeks| on a budget| without burning out))",
                   "{n} ((things|lessons|mistakes|tips)) ((I learned|we made|about)) {pt_obj}",
                   "((The|A)) ((beginner's|honest|practical|no-nonsense)) guide to {pt_obj}",
                   "((What|Everything)) ((nobody tells you|I wish I knew)) about {pt_obj}",
                   "{pt_obj_cap}: ((a review|what worked|a year in|the good and the bad))",
                   "((Is|Why is)) {pt_obj} ((worth it|overrated|harder than it looks)) in {year}?",
             "((My|Our)) {pt_obj} ((setup|routine|stack|plan)) ((for|in)) {year}",
             "((Notes|Lessons|Thoughts)) from {n} ((months|years|weeks)) of {pt_obj}",
             "((Stop|Start|Keep)) {pt_gerund}((| - here's why| - seriously| this {month}))",
             "((A|One)) {pt_obj} ((mistake|habit|trick)) that ((cost me|saved me|changed)) ((${amount}|a year|everything))",
             "{pt_obj_cap} ((in|on|for)) (({city}|a budget|small teams|beginners)): ((a guide|what I learned|tips))",
             "((Week|Day|Month)) {n} of {pt_obj}((| - update| - still going| - honest update))",
             "((How|Why)) ((I|we)) ((finally|actually|almost)) ((quit|started|fixed|loved)) {pt_obj}",
             "{pt_obj_cap} ((vs|or|versus)) {pt_obj}: ((which to pick|my take|the honest answer))",
             "((What|Things)) {n} ((years|months)) of {pt_obj} ((taught me|did to my bank account|changed))",
             "((Ask me|AMA|FAQ)): {pt_obj} ((in|from|near)) {city}"],
    "pt_verb": ["started", "learned", "built", "fixed", "planned", "switched to", "gave up", "paid off", "automated", "moved to"],
    "pt_obj": ["running", "remote work", "a side project", "home brewing", "our onboarding", "a garden", "meal prep",
               "learning Spanish", "freelancing", "a home office", "Postgres", "a small business", "budget travel",
               "a podcast", "our data pipeline", "a newsletter", "minimalism", "sourdough", "a kitchen renovation",
               "cold water swimming", "a four-day week", "home schooling",
               "a capsule wardrobe", "climbing", "selling on Etsy", "a home gym", "van life", "an allotment",
               "learning piano", "bullet journaling", "a standing desk", "our hiring process", "Rust", "Kubernetes",
               "a vegetable patch", "intermittent fasting", "a marathon plan", "living in {city}"],
    "pt_obj_cap": ["Running", "Remote work", "Freelancing", "Meal prep", "Budget travel", "Our data pipeline",
                   "Home brewing", "Learning Spanish", "A home office"],
    "year": ["2024", "2025", "2026"],
    "pt_gerund": ["overplanning", "running every day", "chasing streaks", "buying more gear", "working weekends",
                  "journaling", "batch cooking", "saying yes to everything", "learning in public", "doom-scrolling"],
    "post_body": ["{pb_open} {pb_point} {pb_point2} {pb_close}", "{pb_open} {pb_point} {pb_close}", "{pb_point} {pb_point2} {pb_close}",
             "{pb_point} {pb_point2} {pb_point3} {pb_close}",
             "{pb_open} {pb_point3} {pb_close}"],
    "pb_open": ["((When|Last {month}|A few months ago|Back in {year})) I ((decided to|finally started to|had to)) ((get serious about|try|rethink)) {pt_obj}.",
                "((This|Here)) is ((a short write-up|what I learned|the honest version)) of ((my|our)) ((first|second)) ((year|month|attempt)) with {pt_obj}.",
                "((Plenty of|A lot of|Most)) ((people|guides|posts)) ((say|claim|suggest)) {pt_obj} ((is easy|is simple|takes no time)). ((It isn't|It wasn't for me|Not quite)).",
             "((Quick|Short|Long)) ((update|post|story)) ((on|about)) {pt_obj}, ((since|because|as)) ((a few people asked|{fname} asked|I promised)).",
             "((It's|It has)) been {n} ((weeks|months|years)) since I ((started|took up|committed to)) {pt_obj}((.|, so here's a recap.))",
             "((Everyone|Half my friends|My whole office)) ((seems to be|is|was)) ((into|talking about|trying)) {pt_obj} ((right now|this year|lately)), so ((I|we)) ((gave it a go|joined in|finally tried)).",
             "((This|Today's)) ((post|write-up|entry)) ((covers|is about|walks through)) {pt_obj} ((from|in|around)) {city}."],
    "pb_point": ["The ((first|biggest|hardest)) ((lesson|surprise|mistake)) was ((underestimating the time|spending too much up front|doing it alone|skipping the basics)).",
                 "((Starting|Keeping it)) small ((helped|mattered|made all the difference)): ((ten minutes a day|one evening a week|a single page|a {n}-week plan)).",
                 "((Tools|Gear|Software)) mattered less than ((routine|consistency|having a plan|asking for help)).",
             "((I|We)) ((started|began|tried)) with ((a cheap {item}|second-hand gear|a free app|a library book|YouTube tutorials)) and ((upgraded later|never needed more|regretted nothing)).",
             "((Week|Month)) ((one|two|three)) ((was|felt)) ((brutal|easy|messy|exciting)): ((I|we)) ((kept forgetting|over-did it|got distracted|loved it)).",
             "((The|My)) ((single|one)) ((best|most useful)) ((tip|change|habit)): ((write it down|do it first thing|tell someone|book it in the diary)).",
             "((Living|Working|Doing this)) in {city} ((helped|made it harder|meant)) ((a lot|more than expected|plenty of company)).",
             "((Budget|Money|Cash)) ((was|got)) ((tight|the main constraint|easier than expected)), so ((I|we)) ((borrowed|bought second-hand|DIYed|skipped)) ((most of the gear|the fancy tools|the course|a lot)).",
             "((Mornings|Evenings|Lunch breaks|Weekends)) ((worked best|were the only option|turned out ideal)) ((for me|for us|in the end))((.|, oddly.))",
             "((I|We)) ((underestimated|overestimated|misjudged)) ((how long|how hard|how much fun)) ((it would be|the first month would be|the admin is)).",
             "((Community|Forums|A local group|Reddit)) ((helped|saved me|kept me going)) ((more than|as much as)) ((any guide|the books|paid courses)).",
             "((Rain|Winter|A heatwave|Moving house|A new job)) in {month} ((set me back|paused everything|changed the plan)) for ((a fortnight|{n} weeks|a while)).",
             "((My|Our)) ((kit|setup|stack)) ((now|today|these days)): ((a {item}|an old laptop|two apps|a notebook)), ((nothing fancy|that's it|plus patience)).",
             "((The|One)) ((numbers|stat|metric)) ((that|which)) ((surprised|motivated|scared)) me: (({n}0 hours|${amount}|{n} kg|{n}0 km)) in ((the first month|a year|{n} weeks))."],
    "pb_point2": ["((A friend|My partner|A colleague)), {fname}, ((suggested|pushed me to try|showed me)) ((a simpler approach|tracking progress|a weekly review)).",
                  "((By|After)) ((week {n}|month {n}|{month})) ((things clicked|I'd nearly quit|it had become a habit)).",
             "((Skipping|Missing|Doubling up on)) ((a session|a week|rest days)) ((was|turned out)) ((fine|a mistake|necessary)) ((sometimes|in hindsight|more than once)).",
             "((Talking to|Watching|Reading)) ((people who'd done it|{fname}'s blog|a few YouTubers|old forum threads)) ((saved|cost|gave)) me ((weeks|money|a better plan)).",
             "((If|When)) ((I|we)) ((did it again|restarted|helped a friend)), ((I|we))'d ((start slower|spend less|ask earlier|track more))."],
    "pb_point3": ["((I|We)) ((tracked|logged|wrote down)) ((every session|every pound|each week)) in ((a notebook|a spreadsheet|an app)) and ((it helped|patterns showed up|it kept me honest)).",
                  "((Cost|Budget|Spend)) ((so far|overall|all in)): ((about|roughly|under)) ${amount}((.|, mostly on {pt_cost}.))",
                  "((The|My)) ((best|worst)) ((day|week|moment)) was ((in {city}|on {date}|during {month})), ((when it finally worked|when I nearly gave up|when {fname} joined))."],
    "pt_cost": ["books", "gear", "a course", "software", "coffee", "travel", "ingredients", "tools"],
    "pb_close": ["((If you're|For anyone)) ((thinking about it|starting out|on the fence)), ((start small|just begin|ask for help early))((.|!))",
                 "((More|Part two|A follow-up)) ((soon|next {month}|in a few weeks)).", "((Questions|Thoughts)) welcome in the comments.",
             "((Thanks|Cheers)) for reading((!|.| - {fname}))",
             "((Next up|Coming next|Up next)): {pt_obj}((.|!))",
             "((Would|Will)) ((I|we)) ((do it again|recommend it|keep going))? ((Yes|Probably|Ask me in {month}))((.|!))",
             "((Got|Have)) ((a question|a tip|a story))? ((Drop|Leave|Share)) it ((below|in the comments|with me on {weekday}))((.|!))"],
    # ── email subjects ───────────────────────────────────────────────────
    "email_subject": ["((Re: |Fwd: |RE: |))((Quick question|Follow-up|Update|Catch-up|Next steps)) ((on|about|re)) {es_topic}",
                      "{es_topic_cap} - ((action needed|for review|update|final version|{date}))",
                      "((Invoice|Order|Booking|Ticket)) #{ref} ((confirmation|update|reminder|received))",
                      "((Meeting|Call|Lunch|Sync)) ((on|this|next)) ((Monday|Tuesday|Wednesday|Thursday|Friday|{weekday}))((| at {time}|?))",
                      "((Can we|Could you|Shall we)) ((move|confirm|push)) ((our call|the deadline|Thursday's meeting))((?| to {weekday}?))",
                      "((Thanks|Thank you)) for ((today|your help|the intro|the call))((!|.|))",
             "((Draft|Notes|Slides|Minutes)) ((from|for)) ((today's|Tuesday's|the {month})) ((call|meeting|workshop|review))",
             "((Reminder|Heads up|FYI)): ((deadline|payment|renewal|review)) ((on|due|by)) {date}",
             "((Intro|Introduction)): {fname} <> {fname2}[[ - {company}]]",
             "((Out of office|OOO|Away)) ((until|till|back on)) {date}",
             "((Your|The)) {company} ((order|account|subscription|quote)) ((is ready|has shipped|needs attention|expires {date}))",
             "((Welcome|Congratulations|Thanks)) ((to the team|on the launch|for joining)), {fname}((!|))",
             "((Re: |))((Order|Delivery|Return)) of {item_p} - #{order}",
             "((Your|Re: your)) {month} ((invoice|statement|newsletter)) from {company}",
             "{fname} {lname} - ((CV|application|reference|onboarding docs))",
             "((Quick|Small|Urgent)) ((favour|ask|question)) ((re|about|on)) {es_topic}((| - by {weekday}| - {date}))",
             "((Lunch|Coffee|Drinks)) ((Thursday|Friday|next week|in {city}))((?| with {fname}?))",
             "{n} ((things|items|updates)) ((for|from|before)) ((Monday's|the {month}|tomorrow's)) ((meeting|board|review))"],
    "es_topic": ["the {month} report", "the proposal", "the contract", "Q{n} planning", "the {company} account",
                 "the offsite", "the budget", "the launch", "your application", "the invoice", "the project plan"],
    "es_topic_cap": ["{month} report", "Proposal", "Contract draft", "Q{n} planning", "{company}", "Offsite agenda",
                     "Budget", "Launch checklist", "Project plan", "Board pack"],
    # ── bios ─────────────────────────────────────────────────────────────
    "job": ["{job_given}"],
    "job_l": ["{job_lower}"],
    "bio": ["{job}{at_co}. ((Into|Big on|Usually found doing)) {int1} and {int2}.",
            "{job} | {int1} | {int2}[[ | {city}]]",
            "{job}[[ based in {city}]]. {int_cap} ((at weekends|in my spare time|when I can)).",
            "((Currently|Now|Lately)) {job_l}{at_co}. ((Previously|Before that|Formerly)) {prev}.",
            "{n} years in {field}. ((Weekends are for|Off the clock:|Outside work:)) {int1}.",
            "{int_cap}, {int2} and ((good coffee|long walks|bad puns|too many podcasts)).",
            "((Living|Based|Settled)) in {city}((| with {pet})). ((Love|Into|Obsessed with)) {int1}.",
            "{job}. ((Opinions my own|Views my own|Coffee first)).[[ {emoji}]]",
            "((Mum|Dad|Parent)) of {n}, {job_l}, {int1} ((enthusiast|fan|addict)).",
             "{job_l} by day, {int1} by night((.| {emoji}))",
             "((Ex-|Former )){prev_short}, now {job_l}((| in {city}| at {company})). {int_cap} ((on weekends|in summer|whenever possible)).",
             "((Learning|Studying|Teaching myself)) ((Spanish|Japanese|the guitar|to code|pottery)). {job}[[ @ {company}]].",
             "{city2} ((→|->|to)) {city}. {job}. {int_cap}.",
             "((Running|Building|Growing)) {company}((| in {city}| since {since_year})). {int_cap} ((and|plus)) {int2}.",
             "((Proud|Tired|Happy)) ((parent|owner|human)) of ((two kids|{pet}|a very old car|too many plants)). {job}."],
    "at_co": ["", "", " at {company}", " @ {company}", " with {company}"],
    "int1": ["trail running", "sourdough", "film photography", "board games", "cycling", "jazz", "climbing",
             "gardening", "chess", "travel", "podcasts", "yoga", "cooking", "sci-fi", "football", "open source",
             "wild swimming", "pottery", "birdwatching", "live music", "baking", "hiking", "vintage cars",
             "tennis", "DIY", "knitting", "surfing", "writing", "crosswords", "padel", "ceramics", "kayaking"],
    "int2": ["coffee", "dogs", "good books", "street food", "running", "red wine", "old films", "vinyl",
             "marathons", "camping", "museums", "design", "history", "photography", "the outdoors"],
    "int_cap": ["Trail running", "Sourdough", "Film photography", "Board games", "Cycling", "Climbing",
                "Gardening", "Chess", "Cooking", "Pottery", "Live music", "Hiking", "Surfing", "Writing"],
    "since_year": ["2019", "2020", "2021", "2022", "2023", "2024"],
    "prev_short": ["teacher", "chef", "nurse", "journalist", "banker", "soldier", "barista", "lawyer", "musician", "engineer"],
    "prev": ["{field} at a startup", "teaching", "a decade in {field}", "freelance {field}", "agency life",
             "the civil service", "retail management", "{field} consulting"],
    "field": ["product", "design", "data", "marketing", "operations", "finance", "healthcare", "education",
              "retail", "engineering", "logistics", "sales", "consulting", "customer success", "hospitality", "research"],
    "pet": ["two cats", "a spaniel", "a rescue dog", "a very loud parrot", "the world's laziest cat", "a greyhound"],
}

_cache: Dict[int, Grammar] = {}


def _grammar(rng: np.random.Generator) -> Grammar:
    g = _cache.get(id(rng))
    if g is None:
        if len(_cache) > 8:
            _cache.clear()
        g = Grammar(_RULES, rng, capitalise=True)
        _cache[id(rng)] = g
    g.rng = rng
    return g


def _slots(rng: np.random.Generator, size: int) -> List[Dict[str, str]]:
    from misata.scenarios import _ticket_slot_rows
    rows = _ticket_slot_rows(rng, size)
    merch = ["TESCO STORES", "SAINSBURYS", "WHOLE FOODS", "TARGET", "WALGREENS", "SHELL", "BP", "STARBUCKS",
             "PRET A MANGER", "COSTA", "IKEA", "B&Q", "HOME DEPOT", "CVS", "LIDL", "ALDI", "BOOTS", "ZARA",
             "H&M", "UNIQLO", "NETFLIX.COM", "DELIVEROO", "JUST EAT", "TRAINLINE", "TFL TRAVEL", "WAITROSE",
             "MARKS&SPENCER", "CURRYS", "ARGOS", "KROGER", "SAFEWAY", "CHEVRON", "MCDONALDS", "SUBWAY",
             "GREGGS", "WHSMITH", "SCREWFIX", "HALFORDS", "DECATHLON", "PETS AT HOME"]
    small = ["Blue Door Cafe", "Kiln Coffee", "Maple Bakery", "The Corner Deli", "Riverside Florist",
             "Oak & Ivy", "Little Larder", "Fern Studio", "Harbour Fish Bar", "Two Birds Bakery",
             "The Book Nook", "Ember Pizza", "Saltwater Surf", "Juniper Yoga", "Moss Plants"]
    from misata.scenarios import street_lines
    streets = list(street_lines(rng, size))
    out = []
    for r in rows:
        d = dict(r)
        d.update({
            "merch_u": merch[int(rng.integers(len(merch)))], "city_u": r["city"].upper(),
            "code_u": "".join("ABCDEFGHJKLMNPQRSTUVWXYZ0123456789"[int(rng.integers(34))] for _ in range(int(rng.integers(6, 10)))),
            "small_n": small[int(rng.integers(len(small)))], "small_uu": small[int(rng.integers(len(small)))].upper().replace(" ", ""),
            "company_u": r["company"].upper(), "fname_u": r["fname"].upper(), "lname_u": r["lname"].upper(),
            "dd": f"{int(rng.integers(1, 29)):02d}", "mm": f"{int(rng.integers(1, 13)):02d}",
            "mon_u": ["JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC"][int(rng.integers(12))],
            "bp": f"{int(rng.integers(100, 165))}/{int(rng.integers(60, 100))}", "hr": str(int(rng.integers(52, 118))),
            "temp": f"{rng.normal(37.0, 0.6):.1f}", "spo2": str(int(rng.integers(92, 100))), "rr": str(int(rng.integers(12, 24))),
            "citytag": r["city"].lower().replace(" ", "").replace(".", ""), "monthtag": r["month"].lower(),
            "amount_k": f"{int(rng.integers(12, 480)) * 100:,}",
            "item_p": (f"a {r['item']}" if not r["item"].endswith("s") else r["item"]),
            "street": streets[len(out)],
            "fname2": rows[int(rng.integers(len(rows)))]["fname"], "city2": rows[int(rng.integers(len(rows)))]["city"],
        })
        out.append(d)
    return out


_REGISTER = {"note": "business", "audit": "business", "memo": None, "clinical": "clinical",
             "complaint": "clinical", "discharge": "clinical", "caption": "casual", "post_title": "casual",
             "email_subject": "casual", "post_body": "casual", "bio": "casual", "churn": "casual",
             "cancel": "casual", "return": "casual", "delivery": "casual"}


def render(kind: str, rng: np.random.Generator, size: int, *,
           ratings: Optional[Sequence] = None, context: Optional[Dict[str, Sequence]] = None) -> np.ndarray:
    """``size`` texts of ``kind`` (a key of the rules above, or ``feedback``)."""
    g = _grammar(rng)
    slots = _slots(rng, size)
    for key, vals in (context or {}).items():
        vals = list(vals)
        for i, s in enumerate(slots):
            v = vals[i] if i < len(vals) else None
            if v is not None and str(v).strip() and str(v).lower() not in ("nan", "none"):
                s[key] = str(v)
    if kind == "feedback":
        levels = MicrotextGenerator.normalize_ratings(ratings, size, rng)
        symbols = ["feedback_neg" if lvl <= 2 else "feedback_mid" if lvl == 3 else "feedback_pos"
                   for lvl in levels]
    else:
        symbols = [kind] * size
    if kind == "bio":
        from misata.scenarios import job_titles
        jobs = job_titles(rng, size)
        for i, s in enumerate(slots):
            jg = s.get("job_title") or str(jobs[i])
            s["job_given"], s["job_lower"] = jg, jg.lower()
    out = [g.expand(sym, **s) for sym, s in zip(symbols, slots)]
    detail = {"churn": "churn_detail", "cancel": "cancel_detail", "return": "return_detail",
              "delivery": "delivery_detail", "discharge": "discharge_detail", "audit": "audit_detail"}.get(kind)
    if detail:
        p = 0.85 if kind != "discharge" else 0.9
        def _two(o, s):
            a = g.expand(detail, **s) if rng.random() < p else ""
            b = g.expand(detail, **s) if rng.random() < 0.4 else ""
            return o + a + (b if b != a else "")
        out = [_two(o, s) for o, s in zip(out, slots)]
    sign = {"note": "note_sign", "clinical": "clin_sign", "discharge": "dis_sign"}.get(kind)
    if sign:
        out = [o + (g.expand(sign, **s) if rng.random() < 0.45 else "") for o, s in zip(out, slots)]
    frame = {"churn": "reason_frame", "cancel": "reason_frame", "return": "reason_frame",
             "audit": "audit_frame", "delivery": "delivery_frame"}.get(kind)
    if frame:
        out = [(g.expand(frame, **dict(s, text=o[0].lower() + o[1:])) if rng.random() < 0.35 else o)
               for o, s in zip(out, slots)]
    reg = "casual" if kind == "feedback" else _REGISTER.get(kind)
    if kind in ("post_title", "email_subject", "caption", "complaint"):
        out = vary(out, rng, reg or "casual", rate=0.5, short=True) if reg else out
    elif reg:
        sentences = kind in ("feedback", "post_body", "note", "clinical")
        out = vary(out, rng, reg, styles=sentences)
    return np.array(out, dtype=object)
